/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Kontroler;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import operacije.Operacije;
import server.ObradaKlijentskogZahteva;
import server.PokreniServer;

/**
 *
 * @author Acer
 */
public class ServerskaForma extends javax.swing.JFrame {

    String izabranaR;
    
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
       
        Kontroler.getInstance().setSf(this);
        
        
          PokreniServer ps = new PokreniServer();
          ps.start();
          
        
        
        
          jTextField1.setEnabled(false);
          jTextField2.setEnabled(false); 
          jTextField3.setEnabled(false);
          jTextField4.setEnabled(false);
          jTextField5.setEnabled(false);
        
        
        
        
        
        
        
        for(String s : Kontroler.getInstance().getReci()){
            jComboBoxReci.addItem(s);
        }
        
      
      
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxReci = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButtonPokreniIgru = new javax.swing.JButton();
        jLabelKlijent1 = new javax.swing.JLabel();
        jLabelKlijent2 = new javax.swing.JLabel();
        jLabelPogodaka1 = new javax.swing.JLabel();
        jLabelPokusaja1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPog1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPok1 = new javax.swing.JLabel();
        jLabelPog2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPok2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setPreferredSize(new java.awt.Dimension(50, 50));

        jTextField2.setPreferredSize(new java.awt.Dimension(50, 50));

        jTextField3.setPreferredSize(new java.awt.Dimension(50, 50));

        jTextField4.setPreferredSize(new java.awt.Dimension(50, 50));

        jTextField5.setPreferredSize(new java.awt.Dimension(50, 50));

        jButtonPokreniIgru.setText("POKRENI IGRU");
        jButtonPokreniIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokreniIgruActionPerformed(evt);
            }
        });

        jLabelKlijent1.setText("KLIJENT 1:");

        jLabelKlijent2.setText("KLIJENT 2:");

        jLabel2.setText("/");

        jLabel3.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jComboBoxReci, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButtonPokreniIgru))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabelPogodaka1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelPokusaja1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelKlijent2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPog2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelKlijent1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPog1)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPok1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPok2)))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jComboBoxReci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKlijent1)
                    .addComponent(jLabelPogodaka1)
                    .addComponent(jLabelPokusaja1)
                    .addComponent(jLabel1)
                    .addComponent(jLabelPog1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPok1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKlijent2)
                    .addComponent(jLabelPog2)
                    .addComponent(jLabel3)
                    .addComponent(jLabelPok2))
                .addGap(39, 39, 39)
                .addComponent(jButtonPokreniIgru)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPokreniIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniIgruActionPerformed
       
        
        
        if(Kontroler.getInstance().getListaKlijenata().size()==2){        
        Kontroler.getInstance().setIzabranaRec((String) jComboBoxReci.getSelectedItem());
        izabranaR=(String) jComboBoxReci.getSelectedItem();
        
        Kontroler.getInstance().popuniListuIzabranaSlova(izabranaR);
        
        
        
          jTextField1.setText(izabranaR.charAt(0)+"");
          jTextField2.setText(izabranaR.charAt(1)+"");
          jTextField3.setText(izabranaR.charAt(2)+"");
          jTextField4.setText(izabranaR.charAt(3)+"");
          jTextField5.setText(izabranaR.charAt(4)+"");
        
        
          jButtonPokreniIgru.setEnabled(true);
          
          //POSALJI KLIJENTU ZAHTEV DA JE IGRA ZAPOCETA I OSPOSOBI MU JBUTTON DA MOZE DA POKRENE IGRU
           for(ObradaKlijentskogZahteva okz:Kontroler.getInstance().getListaKlijenata()){
                        okz.obavestiKlijenta(Operacije.OBAVESTI_KLIJENTA, null);
                        
                    }
          
        
        }else{
            JOptionPane.showMessageDialog(null, "Potrebna su dva igraca da bi se igra igrala.");
        }
          
          
          
        
          
        
    }//GEN-LAST:event_jButtonPokreniIgruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokreniIgru;
    private javax.swing.JComboBox<String> jComboBoxReci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelKlijent1;
    private javax.swing.JLabel jLabelKlijent2;
    private javax.swing.JLabel jLabelPog1;
    private javax.swing.JLabel jLabelPog2;
    private javax.swing.JLabel jLabelPogodaka1;
    private javax.swing.JLabel jLabelPok1;
    private javax.swing.JLabel jLabelPok2;
    private javax.swing.JLabel jLabelPokusaja1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    public void prikaziPorukuPobede(String poruka) {

        JOptionPane.showMessageDialog(this, poruka);
    }

    public void updateLabeleServer() {


        ArrayList<ObradaKlijentskogZahteva> klijenti = Kontroler.getInstance().getListaKlijenata();
        
        jLabelPog1.setText(klijenti.get(0).getBrojPogodjenih()+"");
        jLabelPog2.setText(klijenti.get(1).getBrojPogodjenih()+"");
        
        jLabelPok1.setText(klijenti.get(0).getBrojPokusaja()+"");
        jLabelPok2.setText(klijenti.get(1).getBrojPokusaja()+"");

    }

 


    
}
